In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
matrix_1= np.array([[2,3],[4,5]])
print(matrix_1)

[[2 3]
 [4 5]]


In [4]:
matrix_1.shape

(2, 2)

In [5]:
mat_3=np.random.rand(3,3)
print(mat_3)

[[0.01581457 0.62461509 0.51175873]
 [0.0753357  0.77288681 0.71204229]
 [0.89312027 0.21831716 0.2141419 ]]


In [6]:
mat_4= np.random.randint(100,size=(4,5))
print(mat_4)

[[84 40 20 32 95]
 [34 71 55 96 54]
 [51 11 41 44 95]
 [88 55 97 65 62]]


In [7]:
mat_5=np.ones((2,3))
print(mat_5)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
mat_6=np.ones((2,3),dtype=int)
print(mat_6)

[[1 1 1]
 [1 1 1]]


In [9]:
mat_6=np.zeros((2,3))
print(mat_6)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
mat_7=np.zeros((2,3),dtype=int)
print(mat_7)

[[0 0 0]
 [0 0 0]]


In [14]:
mat_8=np.eye(2,3)
print(mat_8)

[[1. 0. 0.]
 [0. 1. 0.]]


In [15]:
mat_9=np.eye(2,3)
print(mat_9.astype(dtype=int))

[[1 0 0]
 [0 1 0]]


In [21]:
mat_9=np.random.randint(100,size=(5,6))
print(mat_9)

[[11 10 48  9 12 93]
 [32 35 47 61 18 97]
 [70 27 20 44 53  4]
 [79 85 77 30  6  8]
 [47 67 74 65  8 75]]


In [22]:
mat_9_trans=np.transpose(mat_9)
print(mat_9_trans)

[[11 32 70 79 47]
 [10 35 27 85 67]
 [48 47 20 77 74]
 [ 9 61 44 30 65]
 [12 18 53  6  8]
 [93 97  4  8 75]]


ADDITION

In [5]:
A=np.array([[2,4],[1,3]])
B=np.array([[2,3,5],[7,1.1]])
C=A+B
print(C)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [6]:
A=np.array([[2,4],[1,3]])
B=np.array([[2,3],[7,1]])
C=A+B
print(C)

[[4 7]
 [8 4]]


subtraction

In [7]:
A= np.random.randint(10,size=(2,3))
B= np.random.randint(20,size=(2,3))
C= A-B
print(C)

[[-12   6  -2]
 [ -3 -10 -10]]


In [9]:
mat1=np.random.randint(10,size=(2,2))
mat2=np.random.randint(10,size=(2,2))

In [12]:
print(mat1)
print(mat2)

[[0 2]
 [1 3]]
[[8 0]
 [6 4]]


In [10]:
np.dot(mat1,mat2)

array([[12,  8],
       [26, 12]])

In [11]:
np.multiply(mat1,mat2)

array([[ 0,  0],
       [ 6, 12]])